### ISSUE TITLE
Infografia

### ISSUE THREAD

**Issue by saul19bautista** [SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-saul19bautista#1]
[infografía_lenguaje_programacion.pdf](https://github.com/SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-saul19bautista/files/15225324/infografia_lenguaje_programacion.pdf)

**Comment by ToniDepp** [comment]
Partes de la infografía: 20/20
Coherencia y pertinencia: 20/20
Organización de la información: 20/20
Diseño de la infografía: 20/20
Creatividad: 15/20

Resultado: 19%/20%

**Comment by josealfredo79** [comment]
bien hecho y revisado...
